name: Promote Flows from Staging

on:
  workflow_dispatch:

env:
  FILES_PATH: flows
  BRANCH_NAME: descope/update-flows

jobs:
  export-and-pr:
    name: Export flows and create pull request
    runs-on: ubuntu-latest

    env:
      DESCOPE_PROJECT_ID: ${{ vars.STAGING_PROJECT_ID }}
      DESCOPE_MANAGEMENT_KEY: ${{ secrets.DESCOPE_MGMT_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Descope CLI
        run: |
          VERSION=$(curl -s https://api.github.com/repos/descope/descopecli/releases/latest | grep tag_name | cut -d '"' -f4)
          curl -sL "https://github.com/descope/descopecli/releases/download/${VERSION}/descopecli_Linux_x86_64.tar.gz" -o descopecli.tar.gz
          tar -xzf descopecli.tar.gz
          chmod +x descopecli
          sudo mv descopecli /usr/local/bin/descopecli

      - name: Export flows from staging
        id: export
        run: |
          mkdir -p tmp_snapshot
          descopecli project snapshot export "$DESCOPE_PROJECT_ID" --path tmp_snapshot --include flows

          mkdir -p ${{ env.FILES_PATH }}
          cp -r tmp_snapshot/flows/* ${{ env.FILES_PATH }}/

          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com

          git add ${{ env.FILES_PATH }}
          git diff --cached --exit-code > /dev/null || echo "has_changes=true" >> $GITHUB_OUTPUT

      - name: Create pull request
        if: steps.export.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
          commit-message: "Update flows from staging"
          title: "Update Descope flows from staging"
          body: |
            ### Description
            This pull request updates the flow definitions in `flows/` based on the latest staging project snapshot.
