name: Promote Flows from Staging

on:
  workflow_dispatch:

env:
  FILES_PATH: "flows"
  BRANCH_NAME: "descope/update-flows"

jobs:
  promote:
    name: Export flows and create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Export Flows from Staging
        id: export
        run: |
          # Export each flow using the API
          for flow in sign-up-or-in sign-in sign-up forgot-password sso-config-request; do
            curl -X POST "https://api.descope.com/v2/mgmt/flow/export" \
              -H "Authorization: Bearer ${{ vars.STAGING_PROJECT_ID }}:${{ secrets.DESCOPE_MGMT_KEY }}" \
              -H "Content-Type: application/json" \
              -d "{\"flowId\": \"$flow\"}" \
              -o "${{ env.FILES_PATH }}/$flow.json"
          done

      - name: Set Git remote to use PAT
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
          assignees: ${{ github.actor }}
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          committer: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          commit-message: "Update Descope flows from staging"
          title: "Update flows from staging"
          body: |
            ### Description
            Updated flow definitions from staging project `${{ vars.STAGING_PROJECT_ID }}`.

            ### Changes
            - Updated sign-up-or-in flow
            - Updated sign-in flow
            - Updated sign-up flow
            - Updated forgot-password flow
            - Updated sso-config-request flow
